#!/usr/bin/env bash
# Emit docs/cli-reference.md from the CLI's own command tree.
#
#   scripts/gen-cli-docs.sh                > docs/cli-reference.md
#   scripts/gen-cli-docs.sh path/to/TREX > docs/cli-reference.md
#
# The source is `TREX agent-context`, which walks the live clap tree — so this
# reference cannot describe a flag the parser does not accept, or miss one it
# does. That is the whole reason the reference is generated rather than written:
# a hand-maintained CLI reference is wrong from the first flag added after it,
# and wrong documentation about an interface is worse than none, because a
# reader has no way to tell which half to trust.
#
# Committed rather than built on demand so it is readable on the web, in a
# checkout, and in a diff. CI regenerates it and fails on any difference — the
# gate is what keeps "committed" from meaning "stale".
#
# Determinism is a requirement, not a nicety: the gate compares bytes. Nothing
# here may depend on the clock, the environment, the host, or the CLI's version
# — a version string in the output would make every release bump a docs diff,
# and a docs gate that goes red for a reason nobody caused gets regenerated
# without being read. Ordering comes from clap's declaration order, which is
# source order.
set -euo pipefail

command -v jq >/dev/null 2>&1 || { echo "error: jq is required" >&2; exit 1; }

BIN="${1:-}"
if [ -z "$BIN" ]; then
    # No path given: build the CLI and use it. `--message-format` rather than a
    # guessed target/debug path, which is wrong under --release, a custom
    # CARGO_TARGET_DIR, or cross-compilation.
    cargo build -p trex-cli --bin trex-cli >&2
    BIN="$(cargo build -p trex-cli --bin trex-cli --message-format=json 2>/dev/null |
        jq -r 'select(.reason == "compiler-artifact") | select(.target.name == "trex-cli") | .executable // empty' |
        tail -n 1)"
fi
[ -n "$BIN" ] && [ -x "$BIN" ] || { echo "error: no TREX binary at '${BIN:-<none>}'" >&2; exit 1; }

DUMP="$("$BIN" agent-context)"

# One jq program for the whole document. Recursion lives in `walk`, so nesting
# depth is clap's business rather than this script's.
printf '%s' "$DUMP" | jq -r '
  # Escape what would otherwise be read as markdown. Help text is prose written
  # for a terminal, and a `*` or `_` in it would silently italicise the table.
  def md: gsub("\\|"; "\\\\|") | gsub("\n"; " ") | gsub("  +"; " ");

  # A positional carries no `long`. Rendering it as `--prompt` would document a
  # flag the parser rejects — the exact class of error generating this file is
  # meant to rule out — so positionals render in angle brackets instead.
  def argname:
    if .long then "`--" + .long + "`" else "`<" + (.name | ascii_upcase) + ">`" end;

  def argrow:
    "| " + argname
    + " | " + (if .takes_value then "yes" else "no" end)
    + " | " + ((.help // "") | md)
    + " |";

  def argtable:
    if (. | length) == 0 then "_No arguments._\n"
    else
      "| Argument | Takes a value | Description |\n"
      + "| --- | --- | --- |\n"
      + ([.[] | argrow] | join("\n")) + "\n"
    end;

  # `path` is the chain of names above this command, so a subcommand renders as
  # `TREX schedule add` rather than as a bare `add`.
  #
  # `$here` is bound once, at the top, and that is load-bearing: inside the
  # `.subcommands[]` pipeline below, `.` is the CHILD, so writing
  # `$path + [.name]` there appends the child name and then lets the recursive
  # call append it a second time. That is not hypothetical — it is what this
  # did, and `TREX permit ls` rendered as `TREX ls ls`.
  #
  # (Note for editors: this jq program is a single-quoted shell string, so an
  # apostrophe anywhere in these comments silently ends it. Avoid possessives.)
  def walk($path; $depth):
    ($path + [.name]) as $here
    | (("#" * $depth) + " `" + ($here | join(" ")) + "`\n")
    + (if .about then "\n" + (.about | md) + "\n" else "" end)
    + "\n" + ([.args[] | select(.global | not)] | argtable)
    + ([.subcommands[] | "\n" + walk($here; $depth + 1)] | join(""));

  "<!-- Generated by scripts/gen-cli-docs.sh. Do not edit by hand. -->\n"
  + "# `TREX` CLI reference\n"
  + "\n"
  + "Every command and option below is read from the parser itself, so this\n"
  + "file cannot drift from what the binary accepts. Regenerate with\n"
  + "`scripts/gen-cli-docs.sh > docs/cli-reference.md`; CI fails if the result\n"
  + "differs from what is committed.\n"
  + "\n"
  + "## Exit codes\n"
  + "\n"
  + "| Code | Name | Meaning |\n"
  + "| --- | --- | --- |\n"
  + "| " + (.exit_codes.ok | tostring) + " | `ok` | The command succeeded. |\n"
  + "| " + (.exit_codes.error | tostring) + " | `error` | The command ran and failed. |\n"
  + "| " + (.exit_codes.usage | tostring) + " | `usage` | The arguments were wrong; nothing was attempted. |\n"
  + "| " + (.exit_codes.host_unreachable | tostring) + " | `host_unreachable` | No host answered. Retrying may help. |\n"
  + "| " + (.exit_codes.timeout | tostring) + " | `timeout` | The host did not reply in time. |\n"
  + "| " + (.exit_codes.access_denied | tostring) + " | `access_denied` | The caller is not allowed to do this. Retrying will not help. |\n"
  + "\n"
  + "## Conventions\n"
  + "\n"
  + "- **JSON output** — " + (.conventions.json_flag | md) + "\n"
  + "- **Async contract** — " + (.conventions.async_contract | md) + "\n"
  + "- **Session scope** — " + (.conventions.session_scope | md) + "\n"
  + "\n"
  + "## Global options\n"
  + "\n"
  + "These apply to every command.\n"
  + "\n"
  + ([.command.args[] | select(.global)] | argtable)
  + "\n"
  + "## Commands\n"
  + "\n"
  + ([.command.subcommands[] | walk(["TREX"]; 3)] | join("\n"))
'
