#!/usr/bin/env bash
# Emit the Homebrew formula for a release, filled in from its signed manifest.
#
#   scripts/gen-homebrew-formula.sh manifest.json > trex.rb
#
# The formula is GENERATED rather than committed with the rest of the packaging
# because every field in it but the name is release-specific: the version, four
# URLs, and four checksums. A committed formula would be wrong the moment it was
# written and would stay wrong until someone remembered to update it — and a
# stale sha256 in a formula fails at `brew install` time, on a user's machine.
#
# The checksums come from the manifest the release workflow signed, so they are
# the same bytes `TREX update` verifies against. Homebrew has no notion of the
# minisign signature; what it inherits is that these digests were signed at
# release time rather than recomputed later from whatever the URL now serves.
#
# `TREX update` refuses to touch a Homebrew-managed install (it detects the
# Cellar path and says `brew upgrade TREX` instead) — two things owning one
# set of files is a state neither can reason about.

set -euo pipefail

MANIFEST="${1:?usage: gen-homebrew-formula.sh <manifest.json>}"
REPO="tiraci/Trex"

command -v jq >/dev/null 2>&1 || { echo "error: jq is required" >&2; exit 1; }

VERSION="$(jq -r '.version' "$MANIFEST")"
[ -n "$VERSION" ] && [ "$VERSION" != "null" ] || { echo "error: no version in $MANIFEST" >&2; exit 1; }

# The formula only carries platforms Homebrew itself runs on. A target in the
# manifest with no Homebrew equivalent (Windows) is simply not represented.
url_for() { echo "https://github.com/${REPO}/releases/download/v${VERSION}/$1"; }

# Emit one `url`/`sha256` pair for a target, or nothing if the release skipped
# that platform — a formula referencing an asset that was never built fails at
# install time with a 404, which reads as a broken tap rather than a missing
# build.
block_for() {
    target="$1"; indent="$2"
    archive="$(jq -r --arg t "$target" '.targets[$t].archive // empty' "$MANIFEST")"
    sha="$(jq -r --arg t "$target" '.targets[$t].sha256 // empty' "$MANIFEST")"
    if [ -z "$archive" ] || [ -z "$sha" ]; then
        echo "warning: the release has no ${target} build; omitting it from the formula" >&2
        return 1
    fi
    printf '%surl "%s"\n' "$indent" "$(url_for "$archive")"
    printf '%ssha256 "%s"\n' "$indent" "$sha"
}

# Six spaces: every block sits two levels deep (on_macos → on_arm).
macos_arm="$(block_for aarch64-apple-darwin '      ' || true)"
macos_intel="$(block_for x86_64-apple-darwin '      ' || true)"
linux_intel="$(block_for x86_64-unknown-linux-gnu '      ' || true)"
linux_arm="$(block_for aarch64-unknown-linux-gnu '      ' || true)"

if [ -z "$macos_arm" ] && [ -z "$macos_intel" ] && [ -z "$linux_intel" ] \
    && [ -z "$linux_arm" ]; then
    echo "error: the release has no Homebrew-installable target" >&2
    exit 1
fi

cat <<RUBY
# Generated by scripts/gen-homebrew-formula.sh from the signed release manifest.
# Do not edit by hand — regenerate for each release.
class TREX < Formula
  desc "Scriptable client and host for TREX agent sessions"
  homepage "https://github.com/${REPO}"
  version "${VERSION}"
  license "Apache-2.0"

RUBY

if [ -n "$macos_arm" ] || [ -n "$macos_intel" ]; then
    echo "  on_macos do"
    if [ -n "$macos_arm" ]; then
        echo "    on_arm do"
        echo "$macos_arm"
        echo "    end"
    fi
    if [ -n "$macos_intel" ]; then
        echo "    on_intel do"
        echo "$macos_intel"
        echo "    end"
    fi
    echo "  end"
    echo
fi

if [ -n "$linux_intel" ] || [ -n "$linux_arm" ]; then
    echo "  on_linux do"
    if [ -n "$linux_intel" ]; then
        echo "    on_intel do"
        echo "$linux_intel"
        echo "    end"
    fi
    # Homebrew's own Linux/ARM support is unofficial, so this block may simply
    # never be selected. It costs one stanza and it is generated from the same
    # signed manifest as the rest; omitting it would make the generator warn
    # about a build that does exist, which is the misleading direction.
    if [ -n "$linux_arm" ]; then
        echo "    on_arm do"
        echo "$linux_arm"
        echo "    end"
    fi
    echo "  end"
    echo
fi

cat <<'RUBY'
  def install
    # Both, always. The CLI and the relay speak a handshake versioned in
    # lockstep, so installing one without the other yields an installation
    # that cannot talk to itself.
    bin.install "TREX"
    bin.install "trex-relay"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/TREX version")
  end
end
RUBY
